// scripts/backup-tables.mjs
//
// Dumps every public table to a JSON file under ./backup-out/. The
// backup workflow then commits + pushes that directory to a separate
// private repo (set via BACKUP_REPO_PATH + BACKUP_REPO_TOKEN secrets).
//
// We use a hardcoded table list rather than information_schema so
// migrations / schema mistakes can't accidentally exfiltrate something.
// New tables added later need to be added here on purpose.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getDb, exitOk, exitFail } from "./_lib/cron.mjs";

// Order doesn't matter for a JSON dump; this is just the explicit list.
//
// Excluded by design:
//   _migrations              - regenerated by re-running migration files
//   admin_login_attempts     - runtime auth log, privacy-sensitive
//   admin_sessions           - cookie state, invalidated by restore anyway
//   magic_link_tokens        - hashed but rotation-only; users get fresh
//                              tokens by requesting again post-restore
//   submit_rate_limits       - runtime rate-limit buckets, regenerate
//
// Everything else - including resume_entries, performances, blog_posts,
// admin_users, etc. - belongs in the backup. A restore from these JSON
// files needs to leave admin able to log in and every artist's resume
// + every show's performances intact.
const TABLES = [
  // Profile + submission lifecycle
  "profiles",
  "pending_submissions",
  "flagged_edits",
  "resumes",
  "resume_entries",
  // Email infrastructure
  "email_log",
  "email_blocklist",
  "email_templates",
  // Public content
  "site_content",
  "blog_posts",
  "announcement_banner",
  "resources",
  "resource_categories",
  // Admin-managed taxonomies / labels
  "disciplines",
  "discipline_categories",
  "areas",
  "unions",
  "ethnicities",
  "event_categories",
  "callboard_post_types",
  // Callboard
  "callboard_posts",
  "callboard_subscriptions",
  // Calendar
  "organizations",
  "productions",
  "performances",
  "production_credits",
  // Curation
  "featured_profiles",
  "marquee_settings",
  "reports",
  // Auth bootstrap (passwords are hashed; trusted devices are tokens
  // that expire on their own).
  "admin_users",
  "admin_trusted_devices",
];

async function main() {
  const outDir = process.env.BACKUP_OUT_DIR || "backup-out";
  mkdirSync(outDir, { recursive: true });

  const db = getDb();
  await db.connect();
  try {
    const totals = {};
    for (const table of TABLES) {
      const res = await db.query(`select * from public.${table}`);
      totals[table] = res.rowCount;
      writeFileSync(
        join(outDir, `${table}.json`),
        JSON.stringify(res.rows, null, 2),
      );
    }
    // Manifest with timestamps + row counts for easy diffing across
    // weekly snapshots.
    writeFileSync(
      join(outDir, "manifest.json"),
      JSON.stringify(
        {
          generated_at: new Date().toISOString(),
          tables: totals,
        },
        null,
        2,
      ),
    );
    exitOk(
      `Dumped ${TABLES.length} tables (${Object.values(totals).reduce(
        (a, b) => a + b,
        0,
      )} rows) to ${outDir}/`,
    );
  } finally {
    await db.end();
  }
}

main().catch((err) => {
  console.error(err);
  exitFail("backup-tables crashed");
});
