-- 006_placeholder_profiles.sql
-- Seed placeholder published profiles so the homepage and (future) directory
-- have something to render during dev. Identifiable by their dev.local emails
-- so they're easy to bulk-delete before launch:
--   delete from profiles where email like '%@dev.ssta.local';

insert into public.profiles
  (slug, full_name, email, pronouns, bio, disciplines, geographic_area,
   playable_age_min, playable_age_max, languages, unions, ethnicities,
   member_since, published)
values
  ('maren-hollis',
   'Maren Hollis',
   'maren@dev.ssta.local',
   'she/her',
   'Director and dramaturg working across new-play development and devised theatre. Based in Tacoma; previously assistant directing at OSF.',
   '{"Director","Playwright"}',
   'Tacoma',
   28, 45,
   '{"English"}',
   '{"SDC"}',
   '{"White / European"}',
   current_date - interval '124 days', true),

  ('august-reyes',
   'August Reyes',
   'august@dev.ssta.local',
   'he/him',
   'Actor with a movement and clown background. Comfortable with stage combat, contact improv, and absurdist text. Based in Olympia.',
   '{"Actor"}',
   'Olympia',
   24, 38,
   '{"English","Spanish"}',
   '{"AEA"}',
   '{"Hispanic / Latino"}',
   current_date - interval '63 days', true),

  ('theo-park',
   'Theo Park',
   'theo@dev.ssta.local',
   'they/them',
   'Music director and rehearsal pianist. MM in collaborative piano. Recent MD credits include Sondheim and Jeanine Tesori revivals around the South Sound.',
   '{"Music Director"}',
   'Tacoma',
   30, 60,
   '{"English","Korean"}',
   '{"AFM"}',
   '{"Asian"}',
   current_date - interval '210 days', true),

  ('imani-whitfield',
   'Imani Whitfield',
   'imani@dev.ssta.local',
   'she/her',
   'Costume designer and stitcher. Period research nerd; specialty in Reconstruction-era and early-20th-century silhouettes. Based in Gig Harbor.',
   '{"Costume Designer"}',
   'Gig Harbor',
   null, null,
   '{"English"}',
   '{"USA"}',
   '{"African American / Black"}',
   current_date - interval '47 days', true),

  ('salma-avery',
   'Salma Avery',
   'salma@dev.ssta.local',
   'she/her',
   'Lighting and projection designer. Background in dance lighting; loves working with movement-based pieces. ETC + Pharos programmer.',
   '{"Lighting Designer","Projection Designer"}',
   'Tacoma',
   null, null,
   '{"English","Arabic"}',
   '{"USA","IATSE"}',
   '{"Middle Eastern / North African"}',
   current_date - interval '15 days', true),

  ('wren-castellanos',
   'Wren Castellanos',
   'wren@dev.ssta.local',
   'they/them',
   'Actor-choreographer focused on physical storytelling and ensemble-built work. Trained at Dell''Arte. Open to new collaborations.',
   '{"Actor","Choreographer"}',
   'Olympia',
   22, 35,
   '{"English","Spanish"}',
   '{"Non-Union"}',
   '{"Hispanic / Latino","Multiracial / Mixed"}',
   current_date - interval '88 days', true),

  ('dorian-kim',
   'Dorian Kim',
   'dorian@dev.ssta.local',
   'he/him',
   'Sound designer and composer. Original score commissions for small-house regional theatre. QLab and Reaper-based workflow.',
   '{"Sound Designer"}',
   'Other South Sound',
   null, null,
   '{"English","Korean"}',
   '{"USA"}',
   '{"Asian"}',
   current_date - interval '5 days', true),

  ('nadia-brennan',
   'Nadia Brennan',
   'nadia@dev.ssta.local',
   'she/her',
   'Playwright and dramaturg. New-play workshops, classical adaptation, and translation work. MFA in playwriting.',
   '{"Playwright"}',
   'Gig Harbor',
   null, null,
   '{"English","French"}',
   '{}',
   '{"White / European"}',
   current_date - interval '301 days', true)
on conflict (slug) do nothing;
